_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.1
            "8":
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
architecture:
    value: MyNeuralNet
batch_size:
    value: 5
dataset:
    value: MNIST
epochs:
    value: 20
learning_rate:
    value: 0.01
